language:
- cpp

dist:
- xenial

arch:
- amd64
- arm64
- ppc64le

os:
- linux
- osx

osx_image:
- xcode12.5

addons:
  apt:
    packages: ghostscript valgrind groff
  homebrew:
    packages: ghostscript valgrind

compiler:
- g++
- clang

script:
- ./autogen.sh
- ./configure
- make
- export PATH=$PWD/bin:$PATH
- git clone https://github.com/frederic-mahe/vsearch-tests.git
- cd vsearch-tests
- bash ./run_all_tests.sh
