language:
- cpp

os:
- linux
- osx

compiler:
- g++
- clang

install:
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install ghostscript; sudo apt-get install groff; else brew install ghostscript; fi

script:
- ./autogen.sh
- ./configure
- make
